travis:
  secure:
    BINSTAR_TOKEN: gr8ECryKD3Ff3RckH7CH4feVtOFQXai/qLU1vDsX+cycsVqOIuTLfgCL31AECGMx9nuMB//PebkNfHEuUra+309rGRzZs75JnCv5H7Ec1/9opU+8mqbpA2cRFIFm/Tf5aRCcZe0HVrwCq6EJGacfeItoezuzju80OPoWAU5IPjjmNbDLFxoEvj6zbEFbh+ecrENUZBO/SKRKBTtI1d4OWjfl8SxMStxEc+d7Pa6WogbYIyzex/zCGJESOOI6GlwoFBxSX4k6eZ2trhHPRVpty69vCXQReazhCzBjOf4kHj54BhYTnuXfYtW49pUD8lUyh5bDTR9eulP1kUd1oMnI5xuk5XGIx82YUry3ak+LgavsnqrpoXZIWs7S+ib+ikcoXHjmWSTLeO1vPg4VUX9bM991U9dJqnOYK6exaTm7zkjhNS5eYH0aPQ4eyshQCPmRGozNNa4GsuNhRuNQFjdvp4kgAkWpUBzdl7DnMyVdHXFFi8xrxZqcqFTKvg26sbWYwN54pplFQ0tH5/gwWcdrJYX9jZQMC5ilRAcwZo3xa5eJQeVqMXj96N8yiMYnplo6YYXR08zewoh/ENptbZZtSPe5Rg4RrSNvmv+yHsoPOy8acyr3/Ga6gfi44x/F4ZA2Qghc6Gjk7fmxac8C1IbvZ/j0mrTXy4mYe5Dg7O8vlXU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
